apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
    type: backend
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    app: springboot-app
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
      type: backend
  template:
    metadata:
      labels:
        app: springboot-app
        type: backend
    spec:
      containers:
        - name: springboot
          image: arizki/springboot:36